### ISSUE TITLE
Configurable prefix

### ISSUE THREAD

**Issue by lusis** [sethfitz/metricsd#10]
I attempted to add support for this myself (no real Scala experience here) but after getting down into the point where coda's metrics library started dumping stuff to graphite by grouped under the metric type, I decided to open an issue.

We like to group our metrics in graphite under "stats.company.<host shortname>. Right now the top-level of `metrics` is hardcoded. I was able to change THAT part but as I discovered the actual type of metric is being injected I _THINK_ by coda's stuff in GraphiteReporter.

I'm thinking this would be a bigger change than the approach I was looking at. I'm willing to give it a shot (been looking for an itch to scratch in Scala) but wanted to see your thoughts.

I'd really like to use metricsd as I'm keen on the additional data types.

**Comment by sethfitz** [comment]
Good call, the top-level `metrics` string could be configurable, probably as `prefix` or something.  Metric types _are_ hardcoded in `metricsd` as well; look for any `new MetricName` in [MetricsServiceHandler](https://github.com/mojodna/metricsd/blob/master/src/main/scala/net/mojodna/metricsd/server/MetricsServiceHandler.scala).

Is the presence of metric type in the name problematic for you (assuming you can override the prefix or eliminate it in favor of feeding it from a client)?

**Comment by sethfitz** [comment]
This was added in c14d4e97cd9dea1a55785cbefcc96166a158e8a2.
