### ISSUE TITLE
Question: can metricsd also send timestamp to graphite

### ISSUE THREAD

**Issue by spatzle** [sethfitz/metricsd#11]
This other project called graphite-relay [https://github.com/markchadwick/graphite-relay#readme]  can send timestamp also, can metricsd do this?

Thanks,

**Comment by sethfitz** [comment]
It does.  Or rather, the underlying [metrics](https://github.com/codahale/metrics) library does.  See [GraphiteReporter](https://github.com/codahale/metrics/blob/master/metrics-graphite/src/main/java/com/yammer/metrics/graphite/GraphiteReporter.java) for more information.
