### ISSUE TITLE
counter decrements will result in error

### ISSUE THREAD

**Issue by skeleton9** [sethfitz/metricsd#7]
I'm using metricsd-0.4.1-jar-with-dependencies.jar  with default settings under Ubuntu 10.04

counter increment works OK for me.
But when send message as "test:-10|c" will get this:

ERROR [2012-02-24 10:25:57,266] net.mojodna.metricsd.server.MetricsServiceHandler: Exception in MetricsServiceHandler
! scala.MatchError: test:-10|c (of class java.lang.String)
!   at net.mojodna.metricsd.server.MetricsServiceHandler$$anonfun$messageReceived$1.apply(MetricsServiceHandler.scala:33)
!   at net.mojodna.metricsd.server.MetricsServiceHandler$$anonfun$messageReceived$1.apply(MetricsServiceHandler.scala:31)
!   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
!   at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
!   at net.mojodna.metricsd.server.MetricsServiceHandler.messageReceived(MetricsServiceHandler.scala:30)
!   at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
!   at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:71)
!   at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
!   at org.jboss.netty.channel.socket.nio.NioDatagramWorker.read(NioDatagramWorker.java:413)
!   at org.jboss.netty.channel.socket.nio.NioDatagramWorker.processSelectedKeys(NioDatagramWorker.java:342)
!   at org.jboss.netty.channel.socket.nio.NioDatagramWorker.run(NioDatagramWorker.java:255)
!   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
!   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
!   at java.lang.Thread.run(Thread.java:636)

**Comment by sethfitz** [comment]
Good find (I guess my graphs only go up and to the right ;-).  It's a matter of tweaking the regex that matches messages; I'll try to get to that in the next few days.

**Comment by sethfitz** [comment]
Fixed in v0.4.2
